test-not-found:
	curl -H "Accept-Language: en" http://localhost:3000/test-not-found
	curl -H "Accept-Language: th" http://localhost:3000/test-not-found

test-bad-request:
	curl -H "Accept-Language: en" http://localhost:3000/test-bad-request
	curl -H "Accept-Language: th" http://localhost:3000/test-bad-request

test-unauthorized:
	curl -H "Accept-Language: en" http://localhost:3000/test-unauthorized
	curl -H "Accept-Language: th" http://localhost:3000/test-unauthorized

test-field-required:
	curl -H "Accept-Language: en" http://localhost:3000/test-field-required
	curl -H "Accept-Language: th" http://localhost:3000/test-field-required

test-username-length:
	curl -H "Accept-Language: en" http://localhost:3000/test-username-length
	curl -H "Accept-Language: th" http://localhost:3000/test-username-length

test-field:
	curl -H "Accept-Language: en" http://localhost:3000/test-field
	curl -H "Accept-Language: th" http://localhost:3000/test-field

